"""add rota (transporte domain)

Revision ID: 2da38a20b055
Revises: 5da4ad5377f1
Create Date: 2026-07-26 00:25:34.921295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da38a20b055'
down_revision: Union[str, None] = '5da4ad5377f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotas',
    sa.Column('origem_cd_id', sa.UUID(), nullable=True),
    sa.Column('origem_filial_id', sa.UUID(), nullable=True),
    sa.Column('destino_cd_id', sa.UUID(), nullable=True),
    sa.Column('destino_filial_id', sa.UUID(), nullable=True),
    sa.Column('capacidade_maxima', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('lead_time_dias', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(destino_cd_id IS NOT NULL AND destino_filial_id IS NULL) OR (destino_cd_id IS NULL AND destino_filial_id IS NOT NULL)', name='ck_rota_destino'),
    sa.CheckConstraint('(origem_cd_id IS NOT NULL AND origem_filial_id IS NULL) OR (origem_cd_id IS NULL AND origem_filial_id IS NOT NULL)', name='ck_rota_origem'),
    sa.ForeignKeyConstraint(['destino_cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['destino_filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['origem_cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['origem_filial_id'], ['filiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotas')
    # ### end Alembic commands ###
