"""add data_conclusao to ordens

Revision ID: 5da4ad5377f1
Revises: cfd5a7198d7a
Create Date: 2026-07-26 00:13:03.766942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da4ad5377f1'
down_revision: Union[str, None] = 'cfd5a7198d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordens_compra', sa.Column('data_conclusao', sa.Date(), nullable=True))
    op.add_column('ordens_transferencia', sa.Column('data_conclusao', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordens_transferencia', 'data_conclusao')
    op.drop_column('ordens_compra', 'data_conclusao')
    # ### end Alembic commands ###
