"""forecast domain

Revision ID: 8082c3c85985
Revises: d4263ee2fbc7
Create Date: 2026-07-25 23:52:16.214422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8082c3c85985'
down_revision: Union[str, None] = 'd4263ee2fbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classificacoes_item',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('curva_abc', sa.Enum('A', 'B', 'C', name='curva_abc'), nullable=False),
    sa.Column('curva_pqr', sa.Enum('P', 'Q', 'R', name='curva_pqr'), nullable=False),
    sa.Column('coeficiente_variacao', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('calculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_vendas',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('cd_id', sa.UUID(), nullable=True),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(cd_id IS NOT NULL AND filial_id IS NULL) OR (cd_id IS NULL AND filial_id IS NOT NULL)', name='ck_historico_vendas_elo'),
    sa.ForeignKeyConstraint(['cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projecoes',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('cd_id', sa.UUID(), nullable=True),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('horizonte_dias', sa.Integer(), nullable=False),
    sa.Column('quantidade_projetada', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('modelo_utilizado', sa.String(length=50), nullable=False),
    sa.Column('ajuste_aplicado_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sku_similar_utilizado_id', sa.UUID(), nullable=True),
    sa.Column('gerado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(cd_id IS NOT NULL AND filial_id IS NULL) OR (cd_id IS NULL AND filial_id IS NOT NULL)', name='ck_projecoes_elo'),
    sa.ForeignKeyConstraint(['cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['sku_similar_utilizado_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ajustes_projecao',
    sa.Column('sku_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('escopo', sa.Enum('ITEM', 'FORNECEDOR', name='escopo_ajuste'), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('data_limite', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ajustes_projecao')
    op.drop_table('projecoes')
    op.drop_table('historico_vendas')
    op.drop_table('classificacoes_item')
    # ### end Alembic commands ###
