"""drp core domain

Revision ID: cfd5a7198d7a
Revises: 8082c3c85985
Create Date: 2026-07-26 00:00:24.496676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd5a7198d7a'
down_revision: Union[str, None] = '8082c3c85985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_compra',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('destino_cd_id', sa.UUID(), nullable=True),
    sa.Column('destino_filial_id', sa.UUID(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('data_solicitacao', sa.Date(), nullable=False),
    sa.Column('data_previsao', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SUGERIDA', 'APROVADA', 'EM_TRANSITO', 'CONCLUIDA', 'CANCELADA', name='status_ordem_compra'), nullable=False),
    sa.Column('score_criticidade', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('justificativa', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destino_cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['destino_filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_transferencia',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('origem_cd_id', sa.UUID(), nullable=True),
    sa.Column('origem_filial_id', sa.UUID(), nullable=True),
    sa.Column('destino_cd_id', sa.UUID(), nullable=True),
    sa.Column('destino_filial_id', sa.UUID(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('data_embarque_sugerida', sa.Date(), nullable=False),
    sa.Column('data_chegada_estimada', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SUGERIDA', 'APROVADA', 'EM_TRANSITO', 'CONCLUIDA', 'CANCELADA', name='status_ordem_transferencia'), nullable=False),
    sa.Column('score_criticidade', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('justificativa', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(destino_cd_id IS NOT NULL AND destino_filial_id IS NULL) OR (destino_cd_id IS NULL AND destino_filial_id IS NOT NULL)', name='ck_ordem_transf_destino'),
    sa.CheckConstraint('(origem_cd_id IS NOT NULL AND origem_filial_id IS NULL) OR (origem_cd_id IS NULL AND origem_filial_id IS NOT NULL)', name='ck_ordem_transf_origem'),
    sa.ForeignKeyConstraint(['destino_cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['destino_filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['origem_cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['origem_filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_estoque_snapshots',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('cd_id', sa.UUID(), nullable=True),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('necessidade_liquida', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('status', sa.Enum('EXCESSO', 'ADEQUADO', 'BAIXA_EXPOSICAO_RUPTURA', 'ELEVADA_EXPOSICAO_RUPTURA', 'RUPTURA', 'RUPTURA_DRP', name='status_ruptura'), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(cd_id IS NOT NULL AND filial_id IS NULL) OR (cd_id IS NULL AND filial_id IS NOT NULL)', name='ck_status_snapshot_elo'),
    sa.ForeignKeyConstraint(['cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_estoque_snapshots')
    op.drop_table('ordens_transferencia')
    op.drop_table('ordens_compra')
    # ### end Alembic commands ###
