"""initial schema

Revision ID: d4263ee2fbc7
Revises: 
Create Date: 2026-07-25 23:42:41.816982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4263ee2fbc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_distribuicao',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('compradores',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('departamentos',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('grupos_compras',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissoes',
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('segmentos',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('filiais',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cd_supridor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cd_supridor_id'], ['centros_distribuicao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('fornecedores',
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('grupo_compras_id', sa.UUID(), nullable=True),
    sa.Column('previsao_gatilho_dias', sa.Integer(), nullable=True),
    sa.Column('pedido_minimo_valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data_limite_pedido', sa.Enum('NENHUM', 'INICIO_MES', 'QUINZENAL', 'FIM_MES', 'OUTRO', name='data_limite_pedido'), nullable=False),
    sa.Column('cobertura_estoque_manual_habilitada', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_compras_id'], ['grupos_compras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('perfis_acesso',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grupo_compras_id', sa.UUID(), nullable=True),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['grupo_compras_id'], ['grupos_compras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('skus',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('departamento_id', sa.UUID(), nullable=True),
    sa.Column('segmento_id', sa.UUID(), nullable=True),
    sa.Column('comprador_id', sa.UUID(), nullable=True),
    sa.Column('sku_similar_id', sa.UUID(), nullable=True),
    sa.Column('custo_aquisicao', sa.Enum('ELEVADO', 'INTERMEDIARIO', 'BAIXO', name='custo_aquisicao'), nullable=True),
    sa.Column('criticidade_resultado', sa.Enum('VITAL', 'INTERMEDIARIO', 'ORDINARIO', name='criticidade_resultado'), nullable=True),
    sa.Column('comprabilidade', sa.Enum('COMPLEXO', 'DIFICIL', 'PREVISIVEL', name='comprabilidade'), nullable=True),
    sa.Column('frequencia_saida', sa.Enum('POPULAR', 'INTERMEDIARIA', 'RARO', name='frequencia_saida'), nullable=True),
    sa.Column('perfil_demanda', sa.String(length=50), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), nullable=True),
    sa.Column('estoque_seguranca', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('ponto_pedido', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('estoque_maximo', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('cobertura_estoque_manual_dias', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['compradores.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], ),
    sa.ForeignKeyConstraint(['sku_similar_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('estoques_bloqueados',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('cd_id', sa.UUID(), nullable=True),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('BLOQUEADO', 'RESERVADO', 'AVARIA', name='tipo_bloqueio'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(cd_id IS NOT NULL AND filial_id IS NULL) OR (cd_id IS NULL AND filial_id IS NOT NULL)', name='ck_estoque_bloqueado_elo'),
    sa.ForeignKeyConstraint(['cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoques_transito',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('origem_fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('origem_cd_id', sa.UUID(), nullable=True),
    sa.Column('destino_cd_id', sa.UUID(), nullable=True),
    sa.Column('destino_filial_id', sa.UUID(), nullable=True),
    sa.Column('quantidade_solicitada', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantidade_recebida', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('data_previsao_chegada', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destino_cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['destino_filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['origem_cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['origem_fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfis_permissoes',
    sa.Column('perfil_id', sa.UUID(), nullable=False),
    sa.Column('permissao_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis_acesso.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id')
    )
    op.create_table('saldos_estoque',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('cd_id', sa.UUID(), nullable=True),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(cd_id IS NOT NULL AND filial_id IS NULL) OR (cd_id IS NULL AND filial_id IS NOT NULL)', name='ck_saldo_estoque_elo'),
    sa.ForeignKeyConstraint(['cd_id'], ['centros_distribuicao.id'], ),
    sa.ForeignKeyConstraint(['filial_id'], ['filiais.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('perfil_acesso_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfil_acesso_id'], ['perfis_acesso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('logs_decisao',
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('tipo_autor', sa.Enum('SISTEMA', 'USUARIO', name='tipo_autor'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motivos_silenciamento',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('escopo', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motivos_silenciamento')
    op.drop_table('logs_decisao')
    op.drop_table('usuarios')
    op.drop_table('saldos_estoque')
    op.drop_table('perfis_permissoes')
    op.drop_table('estoques_transito')
    op.drop_table('estoques_bloqueados')
    op.drop_table('skus')
    op.drop_table('perfis_acesso')
    op.drop_table('fornecedores')
    op.drop_table('filiais')
    op.drop_table('segmentos')
    op.drop_table('permissoes')
    op.drop_table('grupos_compras')
    op.drop_table('departamentos')
    op.drop_table('compradores')
    op.drop_table('centros_distribuicao')
    # ### end Alembic commands ###
